AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  voltage-api

  SAM Template for voltage-api

Globals:
  Function:
    Runtime: python3.11
    Timeout: 3
    Environment:
      Variables:
        TABLE_NAME: !Ref ReportsTable
        REGION_NAME: !Ref AWS::Region

Resources:

  AddNewReport:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/new_report
      Handler: new_report.lambda_handler
      Architectures:
        - x86_64
      Events:
        VoltageAPI:
          Type: Api
          Properties:
            Path: /reports
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ReportsTable

  ListLastReports:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/list_last
      Handler: list_last.lambda_handler
      Architectures:
        - x86_64
      Events:
        VoltageAPI:
          Type: Api
          Properties:
            Path: /last_reports
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ReportsTable

  ListStationReports:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/list_reports
      Handler: list_reports.lambda_handler
      Architectures:
        - x86_64
      Events:
        VoltageAPI:
          Type: Api
          Properties:
            # TODO: update path
            Path: /reports/{station}
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ReportsTable

  StationLastReport:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/last_report
      Handler: last_report.lambda_handler
      Architectures:
        - x86_64
      Events:
        VoltageAPI:
          Type: Api
          Properties:
            # TODO: update path
            Path: /last_reports/{station}
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ReportsTable

  StationReportCounts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/report_counts
      Handler: report_counts.lambda_handler
      Architectures:
        - x86_64
      Events:
        VoltageAPI:
          Type: Api
          Properties:
            # TODO: update path
            Path: /reports/{station}/count
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ReportsTable

  ReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: station
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: station
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
