STATIONS = frozenset([
    'Acatlán',
    'Agua Caliente',
    'Almoyola',
    'Ayutla',
    'Cacalutla',
    'Caleta Campos',
    'Caracol',
    'Cd Altamirano',
    'Cerro de Oro',
    'Chazumba',
    'Cienequilla',
    'Cofadia Juárez',
    'Colomilla',
    'Constitución',
    'Corral Piedra',
    'Cuajimoloyas',
    'El Carrizo',
    'El Cortés',
    'El Duin',
    'El Herradero',
    'El Jardin',
    'El Portezuelo',
    'El Veinte',
    'El Venado',
    'Guixe',
    'Huamelula SP',
    'Huazolotitlán SM',
    'Huehuetán',
    'Humo Chico',
    'Infiernillo',
    'Joluta',
    'La Central',
    'La Piedra',
    'La Pintada',
    'La Reforma',
    'La Villita',
    'La Virgen',
    'Lachiquiri',
    'Las Adjuntas',
    'Las Garzas',
    'Las Mesas',
    'Las Peñas',
    'Las Vigas',
    'Llano Grande',
    'Llanos Amuzgos',
    'M Tacubaya',
    'Marquelia',
    'Maruata',
    'Mazatán SV',
    'Mezcala',
    'Mitlalcingo',
    'Mixtepec SP',
    'Mixtequilla',
    'Morelos',
    'Ojo de Agua',
    'Olinalá',
    'Palma Sola',
    'Pantla',
    'Papanoa',
    'Petatlán',
    'Piedra Grande',
    'Pilcaya',
    'Providencia',
    'Pto Bálsamo',
    'Puerto Angel',
    'Pénjamo',
    'Quetzalapa',
    'Riv Tonameca',
    'San Gerónimo',
    'San Jerónimo',
    'San Mateo',
    'San Pedro',
    'San Telmo',
    'Santa Lucia',
    'Sola de Vega',
    'Tamazulapam',
    'Tangolunda',
    'Tecomatlán',
    'Tehuacán',
    'Tehuitzingo',
    'Temazcal',
    'Tenango',
    'Teojomulco SD',
    'Tepeji',
    'Tequixtepec',
    'Tetitlán',
    'Tlachichilco',
    'Tlacotepec',
    'Tonalapa',
    'Troncones',
    'Tututepec',
    'Vigastepec',
    'Vista Hermosa',
    'Yucudaa',
    'Zihuatanejo'
])
